name: Publish

on:
  release:
    types: [created]
  push:
    branches:
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    steps:
      - uses: actions/checkout@v3

      - name: Gets semantic release info
        id: semantic_release_info
        uses: fingerprintjs/action-semantic-release-info@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: https://npm.pkg.github.com/

      - uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Package install
        run: pnpm install --frozen-lockfile

      - name: Update package.json version
        uses: jossef/action-set-json-field@v2.1
        with:
          file: packages/core/package.json
          field: version
          value: ${{ steps.semantic_release_info.outputs.git_tag }}

      - name: Push changes
        uses: ad-m/github-push-action@v0.6.0
        with:
          github_token: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
          tags: true

      - name: Publish package
        run: pnpm run release
        env:
          NODE_AUTH_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}

      - name: Create GitHub Release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.PACKAGE_GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.semantic_release_info.outputs.git_tag }}
          release_name: ${{ steps.semantic_release_info.outputs.git_tag }}
          body: ${{ steps.semantic_release_info.outputs.notes }}
          draft: false
          prerelease: false
